/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const getDeviceSummary = `query GetDeviceSummary($id: ID!) {
  getDeviceSummary(id: $id) {
    customerName
    deviceList
    id
    threatList
    totalDevices
  }
}
`;
export const listDeviceSummarys = `query ListDeviceSummarys(
  $filter: ModelDeviceSummaryFilterInput
  $limit: Int
  $nextToken: String
) {
  listDeviceSummarys(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      customerName
      deviceList
      id
      threatList
      totalDevices
    }
    nextToken
  }
}
`;
export const getDevice = `query GetDevice($id: ID!) {
  getDevice(id: $id) {
    id
    adUsers
    threats
    alarmInfos
    flows
    medicalUtilizationRecords
    _createdAt
    _updatedAt
    adminClassified
    alarmCount
    alarmInfoMap
    assetSgt
    autoGroupSets
    avMatchScore
    avVendor
    behaviorState
    blacklistEnforceStatus
    blockAllExternalFlows
    certInfo
    classificationProfileId
    classificationScore
    classificationSource
    classificationState
    classifyInProgress
    criticality
    currIpAddress
    currentUser
    currentUserAccountName
    customerName
    deleteDevice
    deviceCategory
    deviceDescr
    deviceStatusFlags
    deviceType
    deviceTypeDerived
    deviceTypeImg
    dhcpClassId
    dhcpHostname
    dhcpOptions
    dhcpPresent
    dicomAETitle
    dontInherit
    droppingVectors
    encMethod
    entityType
    equipmentGuid
    evalBehaviorAnomalies
    finalSgt
    firstSeen
    fqdn
    fwFlowBaselineEnforceStatus
    groupList
    guestDevice
    hasADInfo
    hasAlarms
    hasAntivirus
    hasAssetTag
    hasClearedAlarms
    hasDeviceAppsInfo
    hasExternalFlows
    hasFlowVectors
    hasInternalFlows
    hasPhiData
    hasUserDetails
    incidentScore
    infobloxInfo
    iotEndpoint
    ipAddress
    ipBindingExpiryTime
    isAgedOut
    isBlacklisted
    isDhcp
    isDicomDest
    knownVulnRiskState
    lastDigProbeScan
    lastHttpScan
    lastIpUpdate
    lastOfflineTs
    lastPasswdScan
    lastRapid7VulnScan
    lastSeen
    lastTenableVulnScan
    lastUnUsedTs
    lastUsed
    lastVulnScan
    logoKey
    longMfgName
    macAddress
    mfgName
    modelNameNo
    openPorts
    osFamily
    osSource
    osSubFamily
    osType
    osVersion
    packetSgt
    passwdScanMap
    portList
    profileGuid
    profileList
    profileMfg
    proxied
    proxy
    recomputeMds2Info
    recomputeVulnerabilities
    resolvedProfile
    riskScore
    serialNo
    siteGuid
    strictEnforcement
    subnet
    swFlowBaselineEnforceStatus
    swVersion
    tags
    tenantGuid
    useState
    vlan
    vlanName
    vulnIds
    vulnScanCounter
    whitelistStatus
  }
}
`;
export const listDevices = `query ListDevices(
  $filter: ModelDeviceFilterInput
  $limit: Int
  $nextToken: String
) {
  listDevices(filter: $filter, limit: $limit, nextToken: $nextToken) {
    items {
      id
      adUsers
      threats
      alarmInfos
      flows
      medicalUtilizationRecords
      _createdAt
      _updatedAt
      adminClassified
      alarmCount
      alarmInfoMap
      assetSgt
      autoGroupSets
      avMatchScore
      avVendor
      behaviorState
      blacklistEnforceStatus
      blockAllExternalFlows
      certInfo
      classificationProfileId
      classificationScore
      classificationSource
      classificationState
      classifyInProgress
      criticality
      currIpAddress
      currentUser
      currentUserAccountName
      customerName
      deleteDevice
      deviceCategory
      deviceDescr
      deviceStatusFlags
      deviceType
      deviceTypeDerived
      deviceTypeImg
      dhcpClassId
      dhcpHostname
      dhcpOptions
      dhcpPresent
      dicomAETitle
      dontInherit
      droppingVectors
      encMethod
      entityType
      equipmentGuid
      evalBehaviorAnomalies
      finalSgt
      firstSeen
      fqdn
      fwFlowBaselineEnforceStatus
      groupList
      guestDevice
      hasADInfo
      hasAlarms
      hasAntivirus
      hasAssetTag
      hasClearedAlarms
      hasDeviceAppsInfo
      hasExternalFlows
      hasFlowVectors
      hasInternalFlows
      hasPhiData
      hasUserDetails
      incidentScore
      infobloxInfo
      iotEndpoint
      ipAddress
      ipBindingExpiryTime
      isAgedOut
      isBlacklisted
      isDhcp
      isDicomDest
      knownVulnRiskState
      lastDigProbeScan
      lastHttpScan
      lastIpUpdate
      lastOfflineTs
      lastPasswdScan
      lastRapid7VulnScan
      lastSeen
      lastTenableVulnScan
      lastUnUsedTs
      lastUsed
      lastVulnScan
      logoKey
      longMfgName
      macAddress
      mfgName
      modelNameNo
      openPorts
      osFamily
      osSource
      osSubFamily
      osType
      osVersion
      packetSgt
      passwdScanMap
      portList
      profileGuid
      profileList
      profileMfg
      proxied
      proxy
      recomputeMds2Info
      recomputeVulnerabilities
      resolvedProfile
      riskScore
      serialNo
      siteGuid
      strictEnforcement
      subnet
      swFlowBaselineEnforceStatus
      swVersion
      tags
      tenantGuid
      useState
      vlan
      vlanName
      vulnIds
      vulnScanCounter
      whitelistStatus
    }
    nextToken
  }
}
`;
