/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateDeviceSummary = `subscription OnCreateDeviceSummary {
  onCreateDeviceSummary {
    customerName
    deviceList
    id
    threatList
    totalDevices
  }
}
`;
export const onUpdateDeviceSummary = `subscription OnUpdateDeviceSummary {
  onUpdateDeviceSummary {
    customerName
    deviceList
    id
    threatList
    totalDevices
  }
}
`;
export const onDeleteDeviceSummary = `subscription OnDeleteDeviceSummary {
  onDeleteDeviceSummary {
    customerName
    deviceList
    id
    threatList
    totalDevices
  }
}
`;
export const onCreateDevice = `subscription OnCreateDevice {
  onCreateDevice {
    id
    adUsers
    threats
    alarmInfos
    flows
    medicalUtilizationRecords
    _createdAt
    _updatedAt
    adminClassified
    alarmCount
    alarmInfoMap
    assetSgt
    autoGroupSets
    avMatchScore
    avVendor
    behaviorState
    blacklistEnforceStatus
    blockAllExternalFlows
    certInfo
    classificationProfileId
    classificationScore
    classificationSource
    classificationState
    classifyInProgress
    criticality
    currIpAddress
    currentUser
    currentUserAccountName
    customerName
    deleteDevice
    deviceCategory
    deviceDescr
    deviceStatusFlags
    deviceType
    deviceTypeDerived
    deviceTypeImg
    dhcpClassId
    dhcpHostname
    dhcpOptions
    dhcpPresent
    dicomAETitle
    dontInherit
    droppingVectors
    encMethod
    entityType
    equipmentGuid
    evalBehaviorAnomalies
    finalSgt
    firstSeen
    fqdn
    fwFlowBaselineEnforceStatus
    groupList
    guestDevice
    hasADInfo
    hasAlarms
    hasAntivirus
    hasAssetTag
    hasClearedAlarms
    hasDeviceAppsInfo
    hasExternalFlows
    hasFlowVectors
    hasInternalFlows
    hasPhiData
    hasUserDetails
    incidentScore
    infobloxInfo
    iotEndpoint
    ipAddress
    ipBindingExpiryTime
    isAgedOut
    isBlacklisted
    isDhcp
    isDicomDest
    knownVulnRiskState
    lastDigProbeScan
    lastHttpScan
    lastIpUpdate
    lastOfflineTs
    lastPasswdScan
    lastRapid7VulnScan
    lastSeen
    lastTenableVulnScan
    lastUnUsedTs
    lastUsed
    lastVulnScan
    logoKey
    longMfgName
    macAddress
    mfgName
    modelNameNo
    openPorts
    osFamily
    osSource
    osSubFamily
    osType
    osVersion
    packetSgt
    passwdScanMap
    portList
    profileGuid
    profileList
    profileMfg
    proxied
    proxy
    recomputeMds2Info
    recomputeVulnerabilities
    resolvedProfile
    riskScore
    serialNo
    siteGuid
    strictEnforcement
    subnet
    swFlowBaselineEnforceStatus
    swVersion
    tags
    tenantGuid
    useState
    vlan
    vlanName
    vulnIds
    vulnScanCounter
    whitelistStatus
  }
}
`;
export const onUpdateDevice = `subscription OnUpdateDevice {
  onUpdateDevice {
    id
    adUsers
    threats
    alarmInfos
    flows
    medicalUtilizationRecords
    _createdAt
    _updatedAt
    adminClassified
    alarmCount
    alarmInfoMap
    assetSgt
    autoGroupSets
    avMatchScore
    avVendor
    behaviorState
    blacklistEnforceStatus
    blockAllExternalFlows
    certInfo
    classificationProfileId
    classificationScore
    classificationSource
    classificationState
    classifyInProgress
    criticality
    currIpAddress
    currentUser
    currentUserAccountName
    customerName
    deleteDevice
    deviceCategory
    deviceDescr
    deviceStatusFlags
    deviceType
    deviceTypeDerived
    deviceTypeImg
    dhcpClassId
    dhcpHostname
    dhcpOptions
    dhcpPresent
    dicomAETitle
    dontInherit
    droppingVectors
    encMethod
    entityType
    equipmentGuid
    evalBehaviorAnomalies
    finalSgt
    firstSeen
    fqdn
    fwFlowBaselineEnforceStatus
    groupList
    guestDevice
    hasADInfo
    hasAlarms
    hasAntivirus
    hasAssetTag
    hasClearedAlarms
    hasDeviceAppsInfo
    hasExternalFlows
    hasFlowVectors
    hasInternalFlows
    hasPhiData
    hasUserDetails
    incidentScore
    infobloxInfo
    iotEndpoint
    ipAddress
    ipBindingExpiryTime
    isAgedOut
    isBlacklisted
    isDhcp
    isDicomDest
    knownVulnRiskState
    lastDigProbeScan
    lastHttpScan
    lastIpUpdate
    lastOfflineTs
    lastPasswdScan
    lastRapid7VulnScan
    lastSeen
    lastTenableVulnScan
    lastUnUsedTs
    lastUsed
    lastVulnScan
    logoKey
    longMfgName
    macAddress
    mfgName
    modelNameNo
    openPorts
    osFamily
    osSource
    osSubFamily
    osType
    osVersion
    packetSgt
    passwdScanMap
    portList
    profileGuid
    profileList
    profileMfg
    proxied
    proxy
    recomputeMds2Info
    recomputeVulnerabilities
    resolvedProfile
    riskScore
    serialNo
    siteGuid
    strictEnforcement
    subnet
    swFlowBaselineEnforceStatus
    swVersion
    tags
    tenantGuid
    useState
    vlan
    vlanName
    vulnIds
    vulnScanCounter
    whitelistStatus
  }
}
`;
export const onDeleteDevice = `subscription OnDeleteDevice {
  onDeleteDevice {
    id
    adUsers
    threats
    alarmInfos
    flows
    medicalUtilizationRecords
    _createdAt
    _updatedAt
    adminClassified
    alarmCount
    alarmInfoMap
    assetSgt
    autoGroupSets
    avMatchScore
    avVendor
    behaviorState
    blacklistEnforceStatus
    blockAllExternalFlows
    certInfo
    classificationProfileId
    classificationScore
    classificationSource
    classificationState
    classifyInProgress
    criticality
    currIpAddress
    currentUser
    currentUserAccountName
    customerName
    deleteDevice
    deviceCategory
    deviceDescr
    deviceStatusFlags
    deviceType
    deviceTypeDerived
    deviceTypeImg
    dhcpClassId
    dhcpHostname
    dhcpOptions
    dhcpPresent
    dicomAETitle
    dontInherit
    droppingVectors
    encMethod
    entityType
    equipmentGuid
    evalBehaviorAnomalies
    finalSgt
    firstSeen
    fqdn
    fwFlowBaselineEnforceStatus
    groupList
    guestDevice
    hasADInfo
    hasAlarms
    hasAntivirus
    hasAssetTag
    hasClearedAlarms
    hasDeviceAppsInfo
    hasExternalFlows
    hasFlowVectors
    hasInternalFlows
    hasPhiData
    hasUserDetails
    incidentScore
    infobloxInfo
    iotEndpoint
    ipAddress
    ipBindingExpiryTime
    isAgedOut
    isBlacklisted
    isDhcp
    isDicomDest
    knownVulnRiskState
    lastDigProbeScan
    lastHttpScan
    lastIpUpdate
    lastOfflineTs
    lastPasswdScan
    lastRapid7VulnScan
    lastSeen
    lastTenableVulnScan
    lastUnUsedTs
    lastUsed
    lastVulnScan
    logoKey
    longMfgName
    macAddress
    mfgName
    modelNameNo
    openPorts
    osFamily
    osSource
    osSubFamily
    osType
    osVersion
    packetSgt
    passwdScanMap
    portList
    profileGuid
    profileList
    profileMfg
    proxied
    proxy
    recomputeMds2Info
    recomputeVulnerabilities
    resolvedProfile
    riskScore
    serialNo
    siteGuid
    strictEnforcement
    subnet
    swFlowBaselineEnforceStatus
    swVersion
    tags
    tenantGuid
    useState
    vlan
    vlanName
    vulnIds
    vulnScanCounter
    whitelistStatus
  }
}
`;
